import Donald from "../../assets/images/Ai-NFT/Donald.svg";
import Cristiano from "../../assets/images/Ai-NFT/Cristiano.svg";
import Lebron from "../../assets/images/Ai-NFT/Lebron.svg";
import Elon from "../../assets/images/Ai-NFT/Elon.svg";
import Jeff from "../../assets/images/Ai-NFT/Jeff.svg";
import Sylvester from "../../assets/images/Ai-NFT/Sylvester.svg";
import Kim from "../../assets/images/Ai-NFT/Kim.svg";
import Volodymyr from "../../assets/images/Ai-NFT/Volodymyr.svg";
import Dana from "../../assets/images/Ai-NFT/Dana.svg";
import Jake from "../../assets/images/Ai-NFT/Jake.svg";
import Bill from "../../assets/images/Ai-NFT/Bill.svg";
import Gautam from "../../assets/images/Ai-NFT/Gautam.svg";
import Bernard from "../../assets/images/Ai-NFT/Bernard.svg";
import Vladimir from "../../assets/images/Ai-NFT/Vladimir.svg";
import Joe from "../../assets/images/Ai-NFT/Joe.svg";
import Tyson from "../../assets/images/Ai-NFT/Tyson.svg";
import Lionel from "../../assets/images/Ai-NFT/Lionel.svg";
import Connor from "../../assets/images/Ai-NFT/Connor.svg";
import Tiger from "../../assets/images/Ai-NFT/Tiger.svg";
import Barak from "../../assets/images/Ai-NFT/Barak.svg";
import Lewis from "../../assets/images/Ai-NFT/Lewis.svg";
import Arnold from "../../assets/images/Ai-NFT/Arnold.svg";
import Tom from "../../assets/images/Ai-NFT/Tom.svg";
import Floyd from "../../assets/images/Ai-NFT/Floyd.svg";
import Kanye from "../../assets/images/Ai-NFT/Kanye.svg";
import Roger from "../../assets/images/Ai-NFT/Roger.svg";
import Serena from "../../assets/images/Ai-NFT/Serena.svg";
import Mike from "../../assets/images/Ai-NFT/Mike.svg";
import Janet from "../../assets/images/Ai-NFT/Janet.svg";
import Gervonta from "../../assets/images/Ai-NFT/Gervonta.svg";
import Khabib from "../../assets/images/Ai-NFT/Khabib.svg";
import Canelo from "../../assets/images/Ai-NFT/Canelo.svg";
import Novak from "../../assets/images/Ai-NFT/Novak.svg";
import Usain from "../../assets/images/Ai-NFT/Usain.svg";
import Virat from "../../assets/images/Ai-NFT/Virat.svg";
import Rafael from "../../assets/images/Ai-NFT/Rafael.svg";
import Christine from "../../assets/images/Ai-NFT/Christine.svg";
import Beyonce from "../../assets/images/Ai-NFT/Beyonce.svg";
import Michael from "../../assets/images/Ai-NFT/Michael.svg";
import Changpeng from "../../assets/images/Ai-NFT/Changpeng.svg";
import Dwayne from "../../assets/images/Ai-NFT/Dwayne.svg";
import Harry from "../../assets/images/Ai-NFT/Harry.svg";
import Mukesh from "../../assets/images/Ai-NFT/Mukesh.svg";

//leaderboard images

import dwayne from "../../assets/images/Ai-NFT/Leaderboard/dwayne.svg";
import beyonce from "../../assets/images/Ai-NFT/Leaderboard/beyonce.svg";
import elon from "../../assets/images/Ai-NFT/Leaderboard/elon.svg";
import barak from "../../assets/images/Ai-NFT/Leaderboard/barak.svg";
import bill from "../../assets/images/Ai-NFT/Leaderboard/bill.svg";
import bernard from "../../assets/images/Ai-NFT/Leaderboard/bernard.svg";
import lebron from "../../assets/images/Ai-NFT/Leaderboard/lebron.svg";
import virat from "../../assets/images/Ai-NFT/Leaderboard/virat.svg";
import donald from "../../assets/images/Ai-NFT/Leaderboard/donald.svg";
import jeff from "../../assets/images/Ai-NFT/Leaderboard/jeff.svg";
import mukesh from "../../assets/images/Ai-NFT/Leaderboard/mukesh.svg";
import connor from "../../assets/images/Ai-NFT/Leaderboard/connor.svg";
import joe from "../../assets/images/Ai-NFT/Leaderboard/joe.svg";
import gautam from "../../assets/images/Ai-NFT/Leaderboard/gautam.svg";
import arnold from "../../assets/images/Ai-NFT/Leaderboard/arnold.svg";
import floyd from "../../assets/images/Ai-NFT/Leaderboard/floyd.svg";
import rafael from "../../assets/images/Ai-NFT/Leaderboard/rafael.svg";
import mike from "../../assets/images/Ai-NFT/Leaderboard/mike.svg";
import lewis from "../../assets/images/Ai-NFT/Leaderboard/lewis.svg";
import michael from "../../assets/images/Ai-NFT/Leaderboard/michael.svg";
import khabib from "../../assets/images/Ai-NFT/Leaderboard/khabib.svg";
import usain from "../../assets/images/Ai-NFT/Leaderboard/usain.svg";
import roger from "../../assets/images/Ai-NFT/Leaderboard/roger.svg";
import serena from "../../assets/images/Ai-NFT/Leaderboard/serena.svg";
import jake from "../../assets/images/Ai-NFT/Leaderboard/jake.svg";
import novak from "../../assets/images/Ai-NFT/Leaderboard/novak.svg";
import sylvester from "../../assets/images/Ai-NFT/Leaderboard/sylvester.svg";
import tom from "../../assets/images/Ai-NFT/Leaderboard/tom.svg";
import canelo from "../../assets/images/Ai-NFT/Leaderboard/canelo.svg";
import volodymyr from "../../assets/images/Ai-NFT/Leaderboard/volodymyr.svg";
import changpeng_2 from "../../assets/images/Ai-NFT/Leaderboard/changpeng_2.svg";
import kanye_2 from "../../assets/images/Ai-NFT/Leaderboard/kanye_2.svg";
import dana from "../../assets/images/Ai-NFT/Leaderboard/dana.svg";
import tiger from "../../assets/images/Ai-NFT/Leaderboard/tiger.svg";
import tyson from "../../assets/images/Ai-NFT/Leaderboard/tyson.svg";
import gervonta from "../../assets/images/Ai-NFT/Leaderboard/Gervonta.svg";
import vladimir from "../../assets/images/Ai-NFT/Leaderboard/vladimir.svg";
import janet from "../../assets/images/Ai-NFT/Leaderboard/janet.svg";
import christine from "../../assets/images/Ai-NFT/Leaderboard/christine.svg";
import harry from "../../assets/images/Ai-NFT/Leaderboard/harry.svg";

export const NftData = [
  {
    id: 1,
    heading: "Crypto NFT #1",
    main_img: Donald,
    name: "Donald Trump",
    score: 149,
    rank: 12,
    id: "3BV2...76D723623",
    instagram_followers: "23m",
    twitter_followers: "87m",
    facebook_followers: "34m",
    forbes: "3b",
    trading_volume: "22",
    last_price: "12.00",
    sale_price: "14.40",
    next_price: "17.28",
    wallet_id1: "be23x......326bdg2v",
    wallet_id2: "be23x......326bdg2v",
    price_1: "14.40",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 2,
    heading: "Crypto NFT #2",
    main_img: Cristiano,
    name: "Cristiano Ronaldo",
    score: 833,
    rank: 1,
    id: "3BV2...76D723623",
    instagram_followers: "565m",
    twitter_followers: "107m",
    facebook_followers: "160m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "jbb267x......126cfh2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 3,
    heading: "Crypto NFT #3",
    main_img: Lebron,
    name: "LeBron James",
    score: 218,
    rank: 10,
    id: "3BV2...76D723623",
    instagram_followers: "136m",
    twitter_followers: "53m",
    facebook_followers: "27m",
    forbes: "1b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "cee3x......gov18g2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 4,
    heading: "Crypto NFT #4",
    main_img: Elon,
    name: "Elon Musk",
    score: 329,
    rank: 6,
    id: "3BV2...76D723623",
    instagram_followers: "3m",
    twitter_followers: "132m",
    facebook_followers: "1m",
    forbes: "192b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 5,
    heading: "Crypto NFT #5",
    main_img: Jeff,
    name: "Jeff Bezos",
    score: 132,
    rank: 13,
    id: "3BV2...76D723623",
    instagram_followers: "4m",
    twitter_followers: "6m",
    facebook_followers: "N/A",
    forbes: "121b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "ms23x......526bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 6,
    heading: "Crypto NFT #6",
    main_img: Sylvester,
    name: "Sylvester Stallone",
    score: 31,
    rank: 30,
    id: "3BV2...76D723623",
    instagram_followers: "16m",
    twitter_followers: "3m",
    facebook_followers: "11m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "ms23x......526bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 7,
    heading: "Crypto NFT #7",
    main_img: Kim,
    name: "Kim Kardashian",
    score: 461,
    rank: 3,
    id: "3BV2...76D723623",
    instagram_followers: "349m",
    twitter_followers: "75m",
    facebook_followers: "35m",
    forbes: "1",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 8,
    heading: "Crypto NFT #8",
    main_img: Volodymyr,
    name: "Volodymyr Zelenskyy",
    score: 24,
    rank: 33,
    id: "3BV2...76D723623",
    instagram_followers: "17m",
    twitter_followers: "7m",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "ms23x......526bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 9,
    heading: "Crypto NFT #9",
    main_img: Dana,
    name: "Dana White",
    score: 18,
    rank: 36,
    id: "3BV2...76D723623",
    instagram_followers: "8m",
    twitter_followers: "6m",
    facebook_followers: "3m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "ms23x......526bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 10,
    heading: "Crypto NFT #10",
    main_img: Jake,
    name: "Jake Paul",
    score: 34,
    rank: 28,
    id: "3BV2...76D723623",
    instagram_followers: "22m",
    twitter_followers: "5m",
    facebook_followers: "6m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 11,
    heading: "Crypto NFT #11",
    main_img: Bill,
    name: "Bill Gates",
    score: 221,
    rank: 8,
    id: "3BV2...76D723623",
    instagram_followers: "8m",
    twitter_followers: "62m",
    facebook_followers: "43m",
    forbes: "107b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 12,
    heading: "Crypto NFT #12",
    main_img: Gautam,
    name: "Gautam Adani",
    score: 59,
    rank: 17,
    id: "3BV2...76D723623",
    instagram_followers: "8m",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "50b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 13,
    heading: "Crypto NFT #13",
    main_img: Bernard,
    name: "Bernard Arnault",
    score: 220,
    rank: 9,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "219b Max",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
    color: "#F4CD68",
  },
  {
    id: 14,
    heading: "Crypto NFT #14",
    main_img: Vladimir,
    name: "Vladimir Putin",
    score: 1,
    rank: 40,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 15,
    heading: "Crypto NFT #15",
    main_img: Joe,
    name: "Joe Biden",
    score: 66,
    rank: 16,
    id: "3BV2...76D723623",
    instagram_followers: "17m",
    twitter_followers: "37m",
    facebook_followers: "11m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 16,
    heading: "Crypto NFT #16",
    main_img: Tyson,
    name: "Tyson Fury",
    score: 11,
    rank: 38,
    id: "3BV2...76D723623",
    instagram_followers: "6m",
    twitter_followers: "2m",
    facebook_followers: "2m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 17,
    heading: "Crypto NFT #17",
    main_img: Lionel,
    name: "Lionel Messi",
    score: 560,
    rank: 2,
    id: "3BV2...76D723623",
    instagram_followers: "445m",
    twitter_followers: "N/A",
    facebook_followers: "114m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 18,
    heading: "Crypto NFT #18",
    main_img: Connor,
    name: "Connor McGregor",
    score: 72,
    rank: 15,
    id: "3BV2...76D723623",
    instagram_followers: "46m",
    twitter_followers: "10m",
    facebook_followers: "15m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 19,
    heading: "Crypto NFT #19",
    main_img: Tiger,
    name: "Tiger Woods",
    score: 12,
    rank: 37,
    id: "3BV2...76D723623",
    instagram_followers: "3m",
    twitter_followers: "4m",
    facebook_followers: "3m",
    forbes: "1",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 20,
    heading: "Crypto NFT #20",
    main_img: Barak,
    name: "Barak Obama",
    score: 225,
    rank: 7,
    id: "3BV2...76D723623",
    instagram_followers: "36m",
    twitter_followers: "133m",
    facebook_followers: "55m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 21,
    heading: "Crypto NFT #21",
    main_img: Lewis,
    name: "Lewis Hamilton",
    score: 45,
    rank: 22,
    id: "3BV2...76D723623",
    instagram_followers: "30m",
    twitter_followers: "8m",
    facebook_followers: "6m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 22,
    heading: "Crypto NFT #22",
    main_img: Arnold,
    name: "Arnold Schwarzenegger",
    score: 53,
    rank: 18,
    id: "3BV2...76D723623",
    instagram_followers: "23m",
    twitter_followers: "5m",
    facebook_followers: "24m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 23,
    heading: "Crypto NFT #23",
    main_img: Tom,
    name: "Tom Brady",
    score: 26,
    rank: 31,
    id: "3BV2...76D723623",
    instagram_followers: "17m",
    twitter_followers: "3m",
    facebook_followers: "5m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 24,
    heading: "Crypto NFT #24",
    main_img: Floyd,
    name: "Floyd Mayweather Jr",
    score: 53,
    rank: 19,
    id: "3BV2...76D723623",
    instagram_followers: "29m",
    twitter_followers: "8m",
    facebook_followers: "15m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 25,
    heading: "Crypto NFT #25",
    main_img: Kanye,
    name: "Kanye West",
    score: 19,
    rank: 33,
    id: "3BV2...76D723623",
    instagram_followers: "18m",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 26,
    heading: "Crypto NFT #26",
    main_img: Roger,
    name: "Roger Federer",
    score: 58,
    rank: 26,
    id: "3BV2...76D723623",
    instagram_followers: "7m",
    twitter_followers: "12m",
    facebook_followers: "18m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 27,
    heading: "Crypto NFT #27",
    main_img: Serena,
    name: "Serena Williams",
    score: 36,
    rank: 27,
    id: "3BV2...76D723623",
    instagram_followers: "16m",
    twitter_followers: "11m",
    facebook_followers: "8m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 28,
    heading: "Crypto NFT #28",
    main_img: Janet,
    name: "Janet Yellen",
    score: 1,
    rank: 42,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 29,
    heading: "Crypto NFT #29",
    main_img: Gervonta,
    name: "Gervonta Davis",
    score: 5,
    rank: 39,
    id: "3BV2...76D723623",
    instagram_followers: "4m",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 30,
    heading: "Crypto NFT #30",
    main_img: Mike,
    name: "Mike Tyson",
    score: 49,
    rank: 21,
    id: "3BV2...76D723623",
    instagram_followers: "20m",
    twitter_followers: "6m",
    facebook_followers: "22m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },

  {
    id: 31,
    heading: "Crypto NFT #31",
    main_img: Novak,
    name: "Novak Djokovic",
    score: 52,
    rank: 29,
    id: "3BV2...76D723623",
    instagram_followers: "12m",
    twitter_followers: "9m",
    facebook_followers: "10m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 32,
    heading: "Crypto NFT #32",
    main_img: Canelo,
    name: "Canelo Álvarez",
    score: 25,
    rank: 32,
    id: "3BV2...76D723623",
    instagram_followers: "15m",
    twitter_followers: "2m",
    facebook_followers: "7m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 33,
    heading: "Crypto NFT #33",
    main_img: Khabib,
    name: "Khabib Nurmagomedov",
    score: 43,
    rank: 24,
    id: "3BV2...76D723623",
    instagram_followers: "35m",
    twitter_followers: "2m",
    facebook_followers: "5m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 34,
    heading: "Crypto NFT #34",
    main_img: Usain,
    name: "Usain Bolt",
    score: 39,
    rank: 25,
    id: "3BV2...76D723623",
    instagram_followers: "12m",
    twitter_followers: "5m",
    facebook_followers: "21m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 35,
    heading: "Crypto NFT #35",
    main_img: Virat,
    name: "Virat Kohli",
    score: 170,
    rank: 11,
    id: "3BV2...76D723623",
    instagram_followers: "65m",
    twitter_followers: "54m",
    facebook_followers: "50m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 36,
    heading: "Crypto NFT #36",
    main_img: Rafael,
    name: "Rafael Nadal",
    score: 50,
    rank: 20,
    id: "3BV2...76D723623",
    instagram_followers: "18m",
    twitter_followers: "16m",
    facebook_followers: "15m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },

  {
    id: 37,
    heading: "Crypto NFT #37",
    main_img: Michael,
    name: "Michael Jordan",
    score: 43,
    rank: 23,
    id: "3BV2...76D723623",
    instagram_followers: "24m",
    twitter_followers: "5m",
    facebook_followers: "11m",
    forbes: "2b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 38,
    heading: "Crypto NFT #38",
    main_img: Changpeng,
    name: "ChanPeng Zhao",
    score: 20,
    rank: 34,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "8m",
    facebook_followers: "N/A",
    forbes: "11b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 39,
    heading: "Crypto NFT #39",
    main_img: Christine,
    name: "Christine Lagarde",
    score: 1,
    rank: 42,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 40,
    heading: "Crypto NFT #40",
    main_img: Harry,
    name: "Prince Harry",
    score: 1,
    rank: 43,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 41,
    heading: "Crypto NFT #41",
    main_img: Dwayne,
    name: "Dwayne The Rock Johnson",
    score: 452,
    rank: 4,
    id: "3BV2...76D723623",
    instagram_followers: "372m",
    twitter_followers: "17m",
    facebook_followers: "62m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },

  {
    id: 42,
    heading: "Crypto NFT #42",
    main_img: Beyonce,
    name: "Beyonce",
    score: 376,
    rank: 5,
    id: "3BV2...76D723623",
    instagram_followers: "302m",
    twitter_followers: "16m",
    facebook_followers: "57m",
    forbes: "N/A",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
  {
    id: 43,
    heading: "Crypto NFT #43",
    main_img: Mukesh,
    name: "Mukesh Ambani",
    score: 85,
    rank: 14,
    id: "3BV2...76D723623",
    instagram_followers: "N/A",
    twitter_followers: "N/A",
    facebook_followers: "N/A",
    forbes: "84b",
    trading_volume: "10",
    last_price: "10.00",
    sale_price: "12.00",
    next_price: "14.40",
    wallet_id1: "be23x......326bdg2v",
    price_2: "12.00",
    price_3: "10.00",
  },
];

export const Leaderboard = [
  {
    id: 1,
    number: "№4",
    name: "Dwayne The Rock Johnson ",
    img: dwayne,
    score: "453",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 2,
    number: "№5",
    name: "Beyonce",
    img: beyonce,
    score: "376",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 3,
    number: "№6",
    name: "Elon Musk",
    img: elon,
    score: "329",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 4,
    number: "№7",
    name: "Barak Obama",
    img: barak,
    score: "225",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 5,
    number: "№8",
    name: "Bill Gates",
    img: bill,
    score: "221",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 6,
    number: "№9",
    name: "Bernard Arnault",
    img: bernard,
    score: "221",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 7,
    number: "№10",
    name: "LeBron James",
    img: lebron,
    score: "218",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 8,
    number: "№11",
    name: "Virat Kohli",
    img: virat,
    score: "170",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 9,
    number: "№12",
    name: "Donald Trump",
    img: donald,
    score: "149",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 10,
    number: "№13",
    name: "Jeff Bezos",
    img: jeff,
    score: "132",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },

  {
    id: 11,
    number: "№14",
    name: "Mukesh Ambani",
    img: mukesh,
    score: "85",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 12,
    number: "№15",
    name: "Connor McGregor",
    img: connor,
    score: "72",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 13,
    number: "№16",
    name: "Joe Biden",
    img: joe,
    score: "66",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 14,
    number: "№17",
    name: "Gautam Adani",
    img: gautam,
    score: "59",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 15,
    number: "№18",
    name: "Arnold Schwarzenegger",
    img: arnold,
    score: "53",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 16,
    number: "№19",
    name: "Floyd Mayweather Jr",
    img: floyd,
    score: "53",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 17,
    number: "№20",
    name: "Rafael Nadal",
    img: rafael,
    score: "50",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 18,
    number: "№21",
    name: "Mike Tyson",
    img: mike,
    score: "49",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 19,
    number: "№22",
    name: "Lewis Hamilton",
    img: lewis,
    score: "45",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 20,
    number: "№23",
    name: "Michael Jordan",
    img: michael,
    score: "43",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 21,
    number: "№24",
    name: "Khabib Nurmagomedov",
    img: khabib,
    score: "43",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 22,
    number: "№25",
    name: "Usain Bolt",
    img: usain,
    score: "39",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 23,
    number: "№26",
    name: "Roger Federer",
    img: roger,
    score: "38",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 24,
    number: "№27",
    name: "Serena Williams",
    img: serena,
    score: "36",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 25,
    number: "№28",
    name: "Jake Paul",
    img: jake,
    score: "34",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 26,
    number: "№29",
    name: "Novak Djokovic",
    img: novak,
    score: "34",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 27,
    number: "№30",
    name: "Sylvester Stallone",
    img: sylvester,
    score: "31",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 28,
    number: "№31",
    name: "Tom Brady",
    img: tom,
    score: "26",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 29,
    number: "№32",
    name: "Canelo Álvarez",
    img: canelo,
    score: "25",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 30,
    number: "№33",
    name: "Volodymyr Zelenskyy",
    img: volodymyr,
    score: "24",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 31,
    number: "№34",
    name: "ChangPeng Zhao",
    img: changpeng_2,
    score: "20",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 32,
    number: "№35",
    name: "KanYe West",
    img: kanye_2,
    score: "19",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 33,
    number: "№36",
    name: "Dana White",
    img: dana,
    score: "18",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 34,
    number: "№37",
    name: "Tiger Woods",
    img: tiger,
    score: "12",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 35,
    number: "№38",
    name: "Tyson Fury ",
    img: tyson,
    score: "11",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 36,
    number: "№39",
    name: "Gervonta Davis ",
    img: gervonta,
    score: "5",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 37,
    number: "№40",
    name: "Vladimir Putin ",
    img: vladimir,
    score: "1",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 38,
    number: "№41",
    name: "Janet Yellen  ",
    img: janet,
    score: "1",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 39,
    number: "№42",
    name: "Christine Lagarde ",
    img: christine,
    score: "1",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
  {
    id: 40,
    number: "№43",
    name: "Prince Harry ",
    img: harry,
    score: "1",
    address: "3BV2...76D723623",
    dollar_price: "12.00",
  },
];
