import ChainLink from "../../assets/images/Betimg/chainlink.png";
import senegal from "../../assets/images/WorldcupBanner/senegal-mini.webp";
import england from "../../assets/images/WorldcupBanner/england-mini.webp";
import football from "../../assets/images/ActiveBets/football.webp";
import Cricket from "../../assets/images/ActiveBets/cricketnew.webp";
import bitcoin from "../../assets/images/ActiveBets/bitcoin.webp";
import UFC from "../../assets/images/ActiveBets/UFC.webp";
import bnb from "../../assets/images/ActiveBets/bnb.webp";
import busd from "../../assets/images/ActiveBets/busd.webp";
import usdt from "../../assets/images/ActiveBets/usdt.webp";
import eth from "../../assets/images/ActiveBets/eth.webp";

//filter images
import foxCircle from "../../assets/images/foxCircle.webp";
import DXY from "../../assets/images/DXY.webp";
import Bitcoin from "../../assets/images/Bitcoin.svg";
import Ethere from "../../assets/images/FeaturedEvent/Ethereum.webp";
import Football from "../../assets/images/PL.png";
import CricketGrey from "../../assets/images/Cricket.png";
import UFCGrey from "../../assets/images/UFC.png";
import trending from "../../assets/images/Politics.png";
import DXYW from "../../assets/images/DXYW.webp";
import BitcoinW from "../../assets/images/BitcoinW.webp";
import EthereW from "../../assets/images/FeaturedEvent/white-Ethereum.webp";
import CricketW from "../../assets/images/CricketW.webp";
import PoliticsW from "../../assets/images/PoliticsW.webp";
import FootballW from "../../assets/images/FootballW.webp";
import UFCW from "../../assets/images/UFCW.webp";
import twitter from "../../assets/images/ActiveBets/twitter.png";
import currency from "../../assets/images/ActiveBets/currency.png";
import crypto from "../../assets/images/ActiveBets/crypto.png";
import boxing from "../../assets/images/ActiveBets/boxing.png";
import footballicon from "../../assets/images/ActiveBets/footballicon.png";
import CricketNew from "../../assets/images/ActiveBets/cricketnew.png";
import RugbyW from "../../assets/images/RugbyW.png";
import FormulaW from "../../assets/images/FormulaW.png";
import HorseW from "../../assets/images/HorseW.png";
import DartsW from "../../assets/images/DartsW.png";
import VolleyballW from "../../assets/images/VolleyballW.webp";
import GolfW from "../../assets/images/GolfW.png";
import SnookerW from "../../assets/images/SnookerW.png";
import BaseballW from "../../assets/images/BaseballW.webp";
import TennisW from "../../assets/images/TennisW.webp";
import AmericanFootballW from "../../assets/images/AmericanFootballW.webp";
import BasketballW from "../../assets/images/BasketballW.webp";


export const betData = [
  {
    id: 1,
    icon1: football,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },

  {
    id: 2,
    icon1: UFC,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Jon Jones",
    td_3: "500",
    td_4: usdt,
    td_5: "1.15",
  },
  {
    id: 3,
    icon1: Cricket,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Pakistan",
    td_3: "0.25",
    td_4: busd,
    td_5: "1.29",
  },
  {
    id: 4,
    icon1: bitcoin,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Bitcoin",
    td_3: "0.5",
    td_4: eth,
    td_5: "1.97",
  },
];

const Data = [
  {
    id: "1",
    title: "Poha",
    category: "Breakfast",
    price: "$1",
    img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
    desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways. Kanda poha, soya poha, Indori poha, Nagpur Tari Poha are a few examples",
  },
];

export default Data;

export const Filter = [
  {
    id: 1,
    name: "All",
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Bitcoin",
    td_3: "0.5",
    td_4: eth,
    td_5: "1.97",
  },
  {
    id: 2,
    name: "Social Media",
    img: twitter,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Bitcoin",
    td_3: "0.5",
    td_4: eth,
    td_5: "1.97",
  },
  {
    id: 3,
    name: "Currencies",
    img: currency,
    imgW: BitcoinW,
    icon1: bitcoin,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Bitcoin",
    td_3: "0.5",
    td_4: eth,
    td_5: "1.97",
  },
  {
    id: 4,
    name: "Crypto Currencies",
    img: crypto,
    th_1: "Date",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 5,
    name: "Boxing",
    img: boxing,
    imgW: FootballW,
    icon1: football,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 6,
    name: "Cricket",
    img: CricketNew,
    imgW: CricketW,
    icon1: Cricket,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "Pakistan",
    td_3: "0.25",
    td_4: busd,
    td_5: "1.29",
  },
  {
    id: 7,
    name: "UFC",
    img: boxing,
    imgW: UFCW,
     icon1: UFC,
      th_1: "Date",
      th_2: "Event",
      th_3: "Bet Amount",
      th_4: "Blockchain",
      th_5: "Current Odds",
      td_1: "12.01.2022",
      td_2: "Jon Jones",
      td_3: "500",
      td_4: usdt,
      td_5: "1.15",
  },
  {
    id: 8,
    name: "Football",
    img: FootballW,
    imgW: FootballW,
    icon1: football,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 9,
    name: "Formula One",
    img: FormulaW,
    imgW: FormulaW,
    icon1: FormulaW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 10,
    name: "Basketball",
    img: BasketballW,
    imgW: BasketballW,
    icon1: BasketballW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 11,
    name: "Tennis",
    img: TennisW,
    imgW: TennisW,
    icon1: TennisW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 12,
    name: "American Football",
    img: AmericanFootballW,
    imgW: AmericanFootballW,
    icon1: AmericanFootballW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  }, {
    id: 13,
    name: "Baseball",
    img: BaseballW,
    imgW: BaseballW,
    icon1: BaseballW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 14,
    name: "Snooker",
    img: SnookerW,
    imgW: SnookerW,
    icon1: SnookerW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 15,
    name: "Golf",
    img: GolfW,
    imgW: GolfW,
    icon1: GolfW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 16,
    name: "Rugby",
    img: RugbyW,
    imgW: RugbyW,
    icon1: RugbyW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  {
    id: 17,
    name: "Volleyball",
    img: VolleyballW,
    imgW: VolleyballW,
    icon1: VolleyballW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  }, {
    id: 18,
    name: "Darts",
    img: DartsW,
    imgW: DartsW,
    icon1: DartsW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  }, {
    id: 19,
    name: "Horse Racing",
    img: HorseW,
    imgW: HorseW,
    icon1: HorseW,
    th_1: "Date",
    th_2: "Event",
    th_3: "Bet Amount",
    th_4: "Blockchain",
    th_5: "Current Odds",
    td_1: "12.01.2022",
    td_2: "England/France",
    td_3: "1.28",
    td_4: bnb,
    td_5: "2.25",
  },
  

  // {
  //   id: 8,
  //   name: "UFC",
  //   img: UFCGrey,
  //   imgW: UFCW,
  //   icon1: UFC,
  //   th_1: "Date",
  //   th_2: "Event",
  //   th_3: "Bet Amount",
  //   th_4: "Blockchain",
  //   th_5: "Current Odds",
  //   td_1: "12.01.2022",
  //   td_2: "Jon",
  //   td_3: "8800",
  //   td_4: usdt,
  //   td_5: "1.15",
  // },
  // {
  //   id: 9,
  //   name: "UFC",
  //   img: UFCGrey,
  //   imgW: UFCW,
  //   icon1: UFC,
  //   th_1: "Date",
  //   th_2: "Event",
  //   th_3: "Bet Amount",
  //   th_4: "Blockchain",
  //   th_5: "Current Odds",
  //   td_1: "12.01.2022",
  //   td_2: "Jon",
  //   td_3: "8800",
  //   td_4: usdt,
  //   td_5: "1.15",
  // },
  // {
  //   id: 10,
  //   name: "Trending-Event",
  //   img: trending,
  //   th_1: "Date",
  //   th_2: "Event",
  //   th_3: "Bet Amount",
  //   th_4: "Blockchain",
  //   th_5: "Current Odds",
  //   td_1: "12.01.2022",
  //   td_2: "Jon",
  //   td_3: "8800",
  //   td_4: usdt,
  //   td_5: "1.15",
  // },
];

export const Truth2Filter = [
  {
    id: 1,
    name: "All",
    img: foxCircle,
  },
  {
    id: 2,
    name: "DXY",
    img: DXY,
  },
  {
    id: 3,
    name: "Bitcoin",
    img: Bitcoin,
    icon1: bitcoin,
  },
  {
    id: 4,
    name: "Ethereum",
    img: Ethere,
  },
  {
    id: 5,
    name: "Football",
    img: Football,
    icon1: football,
  },
  {
    id: 6,
    name: "Cricket",
    img: CricketGrey,
    icon1: Cricket,
  },
  {
    id: 7,
    name: "UFC",
    img: UFCGrey,
    icon1: UFC,
  },
  {
    id: 8,
    name: "Trending-Event",
    img: trending,
  },
];
